/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dcb97a2f1ef4518a5382d3c
*
* You will get 10% discount for each one of your friends
* 
*/
package com.wishbox.db.wishbox_db.service.base;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.jdbc.core.simple.SimpleJdbcInsert;
import org.springframework.stereotype.Service;

import com.wishbox.db.wishbox_db.entity.Category;
import com.wishbox.db.wishbox_db.service.CategoryService;

//IMPORT RELATIONS
import com.wishbox.db.wishbox_db.entity.Category;
import com.wishbox.db.wishbox_db.entity.User;

@Service
public class CategoryBaseService {

	private static NamedParameterJdbcTemplate jdbcTemplate;
	
		@Autowired
	public void setDataSource(DataSource dataSource) {
		jdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
	}
	


    //CRUD METHODS
    
    //CRUD - CREATE
    	
	public Category insert(Category obj) {
		Long id = jdbcTemplate.queryForObject("select max(_id) from `category`", new MapSqlParameterSource(), Long.class);
		obj.set_id(id == null ? 1 : id + 1);
		String sql = "INSERT INTO `category` (`_id`, `desc`,`isPublic`,`name`,`owner`) VALUES (:id,:desc,:isPublic,:name, :owner )";
			SqlParameterSource parameters = new MapSqlParameterSource()
		    .addValue("id", obj.get_id())
			.addValue("desc", obj.getDesc())
			.addValue("isPublic", obj.getIsPublic())
			.addValue("name", obj.getName())
			.addValue("owner", obj.getOwner());
		
		jdbcTemplate.update(sql, parameters);
		return obj;
	}
	
    	
    //CRUD - REMOVE
    
	public void delete(Long id) {
		String sql = "DELETE FROM `Category` WHERE `_id`=:id";
		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
		
		jdbcTemplate.update(sql, parameters);
	}

    	
    //CRUD - FIND BY Owner
    	
	public List<Category> findByowner(Long idowner) {
		
		String sql = "select * from `Category` WHERE `owner` = :idowner";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
		.addValue("idowner", idowner);
	    
	    return jdbcTemplate.query(sql, parameters, new BeanPropertyRowMapper(Category.class));
	}
    	
    //CRUD - GET ONE
    	
	public Category get(Long id) {
	    
		String sql = "select * from `Category` where `_id` = :id";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
	    
	    return (Category) jdbcTemplate.queryForObject(sql, parameters, new BeanPropertyRowMapper(Category.class));
	}


    	
        	
    //CRUD - GET LIST
    	
	public List<Category> getList() {
	    
		String sql = "select * from `Category`";
		
	    SqlParameterSource parameters = new MapSqlParameterSource();
	    return jdbcTemplate.query(sql, parameters, new BeanPropertyRowMapper(Category.class));
	    
	    
	}

    	
    //CRUD - EDIT
    	
	public Category update(Category obj, Long id) {

		String sql = "UPDATE `Category` SET `desc` = :desc,`isPublic` = :isPublic,`name` = :name , `owner` = :owner  WHERE `_id`=:id";
		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id)
			.addValue("desc", obj.getDesc())
			.addValue("isPublic", obj.getIsPublic())
			.addValue("name", obj.getName())
			.addValue("owner", obj.getOwner());
		jdbcTemplate.update(sql, parameters);
	    return obj;
	}
	
    	
    
    
    
        
    

    
    /*
     * CUSTOM SERVICES
     * 
     *	These services will be overwritten and implemented in CategoryService.java
     */
    

}
