/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dcb97a2f1ef4518a5382d3c
*
* You will get 10% discount for each one of your friends
* 
*/
package com.wishbox.db.wishbox_db.service.base;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.jdbc.core.simple.SimpleJdbcInsert;
import org.springframework.stereotype.Service;

import com.wishbox.db.wishbox_db.entity.Item;
import com.wishbox.db.wishbox_db.service.ItemService;

//IMPORT RELATIONS
import com.wishbox.db.wishbox_db.entity.Category;
import com.wishbox.db.wishbox_db.entity.User;
import com.wishbox.db.wishbox_db.entity.Tag;

@Service
public class ItemBaseService {

	private static NamedParameterJdbcTemplate jdbcTemplate;
	
		@Autowired
	public void setDataSource(DataSource dataSource) {
		jdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
	}
	


    //CRUD METHODS
    
    //CRUD - CREATE
    	
	public Item insert(Item obj) {
		Long id = jdbcTemplate.queryForObject("select max(_id) from `item`", new MapSqlParameterSource(), Long.class);
		obj.set_id(id == null ? 1 : id + 1);
		String sql = "INSERT INTO `item` (`_id`, `createdAt`,`desc`,`isPublic`,`name`,`category`,`createdBy`) VALUES (:id,:createdAt,:desc,:isPublic,:name, :category , :createdBy )";
			SqlParameterSource parameters = new MapSqlParameterSource()
		    .addValue("id", obj.get_id())
			.addValue("createdAt", obj.getCreatedAt())
			.addValue("desc", obj.getDesc())
			.addValue("isPublic", obj.getIsPublic())
			.addValue("name", obj.getName())
			.addValue("category", obj.getCategory())
			.addValue("createdBy", obj.getCreatedBy());
		
		jdbcTemplate.update(sql, parameters);
		return obj;
	}
	
    	
    //CRUD - REMOVE
    
	public void delete(Long id) {
		String sql = "DELETE FROM `Item` WHERE `_id`=:id";
		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
		
		String sql_tags = "DELETE FROM `item_tags` WHERE `id_Item`= :id";
		jdbcTemplate.update(sql_tags, parameters);
		jdbcTemplate.update(sql, parameters);
	}

    	
    //CRUD - FIND BY Category
    	
	public List<Item> findBycategory(Long idcategory) {
		
		String sql = "select * from `Item` WHERE `category` = :idcategory";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
		.addValue("idcategory", idcategory);
	    
	    return jdbcTemplate.query(sql, parameters, new BeanPropertyRowMapper(Item.class));
	}
    	
    //CRUD - FIND BY CreatedBy
    	
	public List<Item> findBycreatedBy(Long idcreatedBy) {
		
		String sql = "select * from `Item` WHERE `createdBy` = :idcreatedBy";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
		.addValue("idcreatedBy", idcreatedBy);
	    
	    return jdbcTemplate.query(sql, parameters, new BeanPropertyRowMapper(Item.class));
	}
    	
    //CRUD - FIND BY Tags
    	
	public List<Item> findBytags(Long idtags) {
		
        String sql = "select * from `Item` WHERE `_id` IN (SELECT `id_Item` FROM `Item_tags` WHERE `id_Tag` = :idtags)";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
		.addValue("idtags", idtags);
	    
	    return jdbcTemplate.query(sql, parameters, new BeanPropertyRowMapper(Item.class));
	}
    	
    //CRUD - GET ONE
    	
	public Item get(Long id) {
	    
		String sql = "select * from `Item` where `_id` = :id";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
	    
	    return (Item) jdbcTemplate.queryForObject(sql, parameters, new BeanPropertyRowMapper(Item.class));
	}


    	
        	
    //CRUD - GET LIST
    	
	public List<Item> getList() {
	    
		String sql = "select * from `Item`";
		
	    SqlParameterSource parameters = new MapSqlParameterSource();
	    return jdbcTemplate.query(sql, parameters, new BeanPropertyRowMapper(Item.class));
	    
	    
	}

    	
    //CRUD - EDIT
    	
	public Item update(Item obj, Long id) {

		String sql = "UPDATE `Item` SET `createdAt` = :createdAt,`desc` = :desc,`isPublic` = :isPublic,`name` = :name , `category` = :category , `createdBy` = :createdBy  WHERE `_id`=:id";
		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id)
			.addValue("createdAt", obj.getCreatedAt())
			.addValue("desc", obj.getDesc())
			.addValue("isPublic", obj.getIsPublic())
			.addValue("name", obj.getName())
			.addValue("category", obj.getCategory())
			.addValue("createdBy", obj.getCreatedBy());
		jdbcTemplate.update(sql, parameters);
	    return obj;
	}
	
    	
    
    
    
        
        
    
    // External relation m:m tags
    public static class Item_tagsService {

    	public static ArrayList<Long> findBy_Item(Long id_Item) {
    		String sql = "select `id_Tag` from Item_tags WHERE `id_Item`=:id_Item";
    		SqlParameterSource parameters = new MapSqlParameterSource()
    			.addValue("id_Item", id_Item);
    	    
    	    List<Long> listId = jdbcTemplate.queryForList(sql, parameters, Long.class);
    		return (ArrayList<Long>) listId;
    	}
    	

    	public static void updateRelation(Long id_Item, ArrayList<Long> tags) {

    		// Delete not in array
    		String in = " and `id_Tag` NOT IN (:tags)";
    		String sql = "DELETE FROM Item_tags WHERE `id_Item`=:id_Item ";
    		
    		if (tags != null && tags.size() > 0)
    			sql = sql + in;
    			
    		SqlParameterSource parameters = new MapSqlParameterSource()
    			.addValue("id_Item", id_Item)
    			.addValue("tags", tags);
    		
    		jdbcTemplate.update(sql, parameters);
    		
    		// Get actual    		
    	    List<Long> actual = ItemService.Item_tagsService.findBy_Item(id_Item);
    	    
    		// Insert new
    		for (Long id_Tag : tags) {
    			if (actual.indexOf(id_Tag) == -1){
    				ItemService.Item_tagsService.insert(id_Item, id_Tag);
    			}
    		}
    		
    	}
    	

    	public static void insert(Long id_Item, Long id_Tag) {
    		Item.Item_tags obj = new Item.Item_tags();
			Long id = jdbcTemplate.queryForObject("select max(_id) FROM Item_tags", new MapSqlParameterSource(), Long.class);
			obj.set_id(id == null ? 1 : id + 1);
			
			String sql = "INSERT INTO Item_tags (`_id`, `id_Item`, `id_Tag` )	VALUES (:id, :id_Item, :id_Tag)";

			MapSqlParameterSource parameters = new MapSqlParameterSource()
				.addValue("id", obj.get_id())
				.addValue("id_Item", id_Item)
				.addValue("id_Tag", id_Tag);

			jdbcTemplate.update(sql, parameters);
    	}

    }
	

    
    /*
     * CUSTOM SERVICES
     * 
     *	These services will be overwritten and implemented in ItemService.java
     */
    

}
