/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dcb97a2f1ef4518a5382d3c
*
* You will get 10% discount for each one of your friends
* 
*/
package com.wishbox.db.wishbox_db.service.base;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.jdbc.core.simple.SimpleJdbcInsert;
import org.springframework.stereotype.Service;

import com.wishbox.db.wishbox_db.entity.Post;
import com.wishbox.db.wishbox_db.service.PostService;

//IMPORT RELATIONS
import com.wishbox.db.wishbox_db.entity.User;

@Service
public class PostBaseService {

	private static NamedParameterJdbcTemplate jdbcTemplate;
	
		@Autowired
	public void setDataSource(DataSource dataSource) {
		jdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
	}
	


    //CRUD METHODS
    
    //CRUD - CREATE
    	
	public Post insert(Post obj) {
		Long id = jdbcTemplate.queryForObject("select max(_id) from `post`", new MapSqlParameterSource(), Long.class);
		obj.set_id(id == null ? 1 : id + 1);
		String sql = "INSERT INTO `post` (`_id`, `content`,`createdAt`,`title`,`updatedAt`,`createdBy`) VALUES (:id,:content,:createdAt,:title,:updatedAt, :createdBy )";
			SqlParameterSource parameters = new MapSqlParameterSource()
		    .addValue("id", obj.get_id())
			.addValue("content", obj.getContent())
			.addValue("createdAt", obj.getCreatedAt())
			.addValue("title", obj.getTitle())
			.addValue("updatedAt", obj.getUpdatedAt())
			.addValue("createdBy", obj.getCreatedBy());
		
		jdbcTemplate.update(sql, parameters);
		return obj;
	}
	
    	
    //CRUD - REMOVE
    
	public void delete(Long id) {
		String sql = "DELETE FROM `Post` WHERE `_id`=:id";
		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
		
		jdbcTemplate.update(sql, parameters);
	}

    	
    //CRUD - FIND BY CreatedBy
    	
	public List<Post> findBycreatedBy(Long idcreatedBy) {
		
		String sql = "select * from `Post` WHERE `createdBy` = :idcreatedBy";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
		.addValue("idcreatedBy", idcreatedBy);
	    
	    return jdbcTemplate.query(sql, parameters, new BeanPropertyRowMapper(Post.class));
	}
    	
    //CRUD - GET ONE
    	
	public Post get(Long id) {
	    
		String sql = "select * from `Post` where `_id` = :id";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
	    
	    return (Post) jdbcTemplate.queryForObject(sql, parameters, new BeanPropertyRowMapper(Post.class));
	}


    	
        	
    //CRUD - GET LIST
    	
	public List<Post> getList() {
	    
		String sql = "select * from `Post`";
		
	    SqlParameterSource parameters = new MapSqlParameterSource();
	    return jdbcTemplate.query(sql, parameters, new BeanPropertyRowMapper(Post.class));
	    
	    
	}

    	
    //CRUD - EDIT
    	
	public Post update(Post obj, Long id) {

		String sql = "UPDATE `Post` SET `content` = :content,`createdAt` = :createdAt,`title` = :title,`updatedAt` = :updatedAt , `createdBy` = :createdBy  WHERE `_id`=:id";
		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id)
			.addValue("content", obj.getContent())
			.addValue("createdAt", obj.getCreatedAt())
			.addValue("title", obj.getTitle())
			.addValue("updatedAt", obj.getUpdatedAt())
			.addValue("createdBy", obj.getCreatedBy());
		jdbcTemplate.update(sql, parameters);
	    return obj;
	}
	
    	
    
    
    
    

    
    /*
     * CUSTOM SERVICES
     * 
     *	These services will be overwritten and implemented in PostService.java
     */
    

}
