/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dcb97a2f1ef4518a5382d3c
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";
import Switch from "@material-ui/core/Switch";
import FormControlLabel from "@material-ui/core/FormControlLabel";

// Custom Actions


// START IMPORT ACTIONS
import CategoryActions from "../redux/actions/CategoryActions";
import ItemActions from "../redux/actions/ItemActions";

// END IMPORT ACTIONS

/** APIs

* actionsCategory.create
*	@description CRUD ACTION create
*
* actionsItem.findBycategory
*	@description CRUD ACTION findBycategory
*	@param Objectid key - Id della risorsa category da cercare
*
* actionsCategory.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsUser.list
*	@description CRUD ACTION list
*
* actionsCategory.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*

**/

class CategoryEdit extends Component {
  // Init category
  constructor(props) {
    super(props);
    this.state = {
      category: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsCategory.loadCategory(this.props.match.params.id);
      this.props.actionsItem.findBycategory(this.props.match.params.id);
    }
    
    this.props.actionsUser.loadUserList();
  }

  // Insert props category in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      category: props.category
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.category._id) {
      this.props.actionsCategory.saveCategory(this.state.category).then(data => {
        this.props.history.push("/categorys/");
      });
    } else {
      this.props.actionsCategory.createCategory(this.state.category).then(data => {
        this.props.history.push("/categorys/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Category Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="desc"
            label="Desc"
            value={this.state.category.desc || ""}
            onChange={Utils.handleChange.bind(this, "category")}
            margin="normal"
            fullWidth
          />
          
          <FormControlLabel
            control={
              <Switch
                id="isPublic"
                checked={this.state.category.isPublic || false}
                onChange={Utils.handleChangeCheck.bind(this, "category", "isPublic")}
                color="primary"
              />
            }
            label="isPublic"
            className="mt-20"
          />
          
          
          <TextField
            id="name"
            label="Name"
            value={this.state.category.name || ""}
            onChange={Utils.handleChange.bind(this, "category")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.category.name && this.state.category.name === ""
              ? { error: true }
              : {})}
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation 1:m owner with User */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="owner">
              Owner
            </InputLabel>
            <Select
              value={this.state.category.owner || ""}
              onChange={Utils.handleChangeSelect.bind(this, "category")}
              inputProps={{
                id: "owner",
                name: "owner"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listUser && this.props.listUser.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with Item */}
          
          <h3>Item</h3>
          {(!this.props.listItem || this.props.listItem.length === 0) && 
            <div>No Item associated</div>
          }
          {this.props.listItem &&
            this.props.listItem.map((item, i) => {
              return (
                <Link to={"/items/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/categorys/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsCategory: bindActionCreators(CategoryActions, dispatch),
    actionsItem: bindActionCreators(ItemActions, dispatch),
  };
};

// Validate types
CategoryEdit.propTypes = { 
  actionsCategory: PropTypes.object.isRequired,
  actionsItem: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    category: state.CategoryEditReducer.category,
    listUser: state.CategoryEditReducer.listUser,
    listItem: state.CategoryEditReducer.listItem
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CategoryEdit);
