/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dcb97a2f1ef4518a5382d3c
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";

// Custom Actions


// START IMPORT ACTIONS
import TagActions from "../redux/actions/TagActions";
import ItemActions from "../redux/actions/ItemActions";

// END IMPORT ACTIONS

/** APIs

* actionsTag.create
*	@description CRUD ACTION create
*
* actionsItem.findBytags
*	@description CRUD ACTION findBytags
*	@param Objectid key - Id della risorsa tags da cercare
*
* actionsTag.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsTag.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*

**/

class TagEdit extends Component {
  // Init tag
  constructor(props) {
    super(props);
    this.state = {
      tag: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsTag.loadTag(this.props.match.params.id);
      this.props.actionsItem.findBytags(this.props.match.params.id);
    }
    
  }

  // Insert props tag in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      tag: props.tag
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.tag._id) {
      this.props.actionsTag.saveTag(this.state.tag).then(data => {
        this.props.history.push("/tags/");
      });
    } else {
      this.props.actionsTag.createTag(this.state.tag).then(data => {
        this.props.history.push("/tags/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Tag Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="name"
            label="Name"
            value={this.state.tag.name || ""}
            onChange={Utils.handleChange.bind(this, "tag")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.tag.name && this.state.tag.name === ""
              ? { error: true }
              : {})}
          />
          
          
          <TextField
            id="type"
            label="Type"
            value={this.state.tag.type || ""}
            onChange={Utils.handleChange.bind(this, "tag")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with Item */}
          
          <h3>Item</h3>
          {(!this.props.listItem || this.props.listItem.length === 0) && 
            <div>No Item associated</div>
          }
          {this.props.listItem &&
            this.props.listItem.map((item, i) => {
              return (
                <Link to={"/items/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/tags/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsTag: bindActionCreators(TagActions, dispatch),
    actionsItem: bindActionCreators(ItemActions, dispatch),
  };
};

// Validate types
TagEdit.propTypes = { 
  actionsTag: PropTypes.object.isRequired,
  actionsItem: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    tag: state.TagEditReducer.tag,
    listItem: state.TagEditReducer.listItem
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(TagEdit);
