/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dcb97a2f1ef4518a5382d3c
*
* You will get 10% discount for each one of your friends
* 
*/
import { combineReducers } from "redux";

// START IMPORT REDUCERS
import CategoryEditReducer from "./CategoryEditReducer";
import CategoryListReducer from "./CategoryListReducer";
import HomeReducer from "./HomeReducer";
import ItemEditReducer from "./ItemEditReducer";
import ItemListReducer from "./ItemListReducer";
import PostEditReducer from "./PostEditReducer";
import PostListReducer from "./PostListReducer";
import TagEditReducer from "./TagEditReducer";
import TagListReducer from "./TagListReducer";
import UserEditReducer from "./UserEditReducer";
import UserListReducer from "./UserListReducer";

// END IMPORT REDUCERS


// CUSTOM REDUCERS
import LoginReducer from "./LoginReducer";
import ProfileReducer from "./ProfileReducer";
import UserEditReducer from "./UserEditReducer";
import UserListReducer from "./UserListReducer";

const rootReducer = combineReducers({
  
  // INSERT HERE YOUR CUSTOM REDUCERS
  LoginReducer,
  ProfileReducer,
  UserEditReducer,
  UserListReducer,

  // START COMBINE REDUCERS
	CategoryEditReducer,
	CategoryListReducer,
	HomeReducer,
	ItemEditReducer,
	ItemListReducer,
	PostEditReducer,
	PostListReducer,
	TagEditReducer,
	TagListReducer,
	UserEditReducer,
	UserListReducer,
 // END COMBINE REDUCERS

});

export default rootReducer;
