/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dcb97a2f1ef4518a5382d3c
*
* You will get 10% discount for each one of your friends
* 
*/

// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// CATEGORY
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const FINDBYOWNER_CATEGORY_SUCCESS = "FINDBYOWNER_CATEGORY_SUCCESS";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const LIST_CATEGORY_SUCCESS = "LIST_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";

// ITEM
export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const FINDBYCATEGORY_ITEM_SUCCESS = "FINDBYCATEGORY_ITEM_SUCCESS";
export const FINDBYCREATEDBY_ITEM_SUCCESS = "FINDBYCREATEDBY_ITEM_SUCCESS";
export const FINDBYTAGS_ITEM_SUCCESS = "FINDBYTAGS_ITEM_SUCCESS";
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const LIST_ITEM_SUCCESS = "LIST_ITEM_SUCCESS";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";

// POST
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const FINDBYCREATEDBY_POST_SUCCESS = "FINDBYCREATEDBY_POST_SUCCESS";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const LIST_POST_SUCCESS = "LIST_POST_SUCCESS";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";

// TAG
export const CREATE_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const DELETE_TAG_SUCCESS = "DELETE_TAG_SUCCESS";
export const GET_TAG_SUCCESS = "GET_TAG_SUCCESS";
export const LIST_TAG_SUCCESS = "LIST_TAG_SUCCESS";
export const UPDATE_TAG_SUCCESS = "UPDATE_TAG_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
